# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v1
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage Information
      run: npm run coverage
    - name: Coveralls Github Action
      uses: coverallsapp/github-action@master
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
